[build]
  command = "echo 'Skipping Vite build for static HTML'"
  publish = "public"

[[edge_functions]]
  path = "/proxy-lando/*"
  function = "proxy"

[[edge_functions]]
  path = "/proxy-assets/*"
  function = "proxy"

[[edge_functions]]
  path = "/proxy-website-files/*"
  function = "proxy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
